name:         runsushi
version:      "0.0.0.0"
synopsis:     Processing inputs and outputs of SusHi
author:       Chan Beom Park
maintainer:   cbpark@gmail.com
license-file: LICENSE
github:       cbpark/runsushi
category:     Physics

ghc-options: -Wall -Wcompat

dependencies:
  - base >= 4.12.0.0 && < 5
  - double-conversion
  - text

executables:
  runsushi:
    main: runsushi.hs
    source-dirs: src
