name:               runsushi
version:            "0.0.0.0"
synopsis:           Processing inputs and outputs of SusHi
author:             Chan Beom Park
maintainer:         cbpark@gmail.com
license-file:       LICENSE
github:             cbpark/runsushi
category:           Physics
extra-source-files: input_template.in

ghc-options: -Wall -Wcompat

dependencies:
  - base >= 4.12.0.0 && < 5
  - attoparsec
  - containers
  - directory
  - double-conversion
  - filepath
  - hashable
  - optparse-generic
  - process
  - text
  - vector

executables:
  runsushi:
    main: runsushi.hs
    source-dirs: src
